version: '3.9'

services:
  nginx:
    image: nginx
    volumes:
      - "./nginx/attiladudas_dev.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./.tmp/media:/media"
    ports:
      - "${APP_PORT-8000}:80"
    environment:
      - NGINX_PORT=80
    restart: on-failure
  
  backend:
    image: attiladudas/backend:latest
    user: backend
    build:
      context: ./backend
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - API_MIGRATIONS_DIR=/migrations
      - API_MEDIA_DIR=/media
      - API_PRIVATE_KEY
      - API_PUBLIC_KEY
    command: ["./run-server", "-host", "0.0.0.0", "-port", "80"]
    volumes:
      - "./.tmp/media:/media"
    ports:
      - "${BACKEND_PORT-8080}:80"
    depends_on:
      - db

  frontend:
    image: frontend
    build: ./frontend
    working_dir: /frontend
    command: >
      bash -c "pnpm install
      && pnpm run dev"
    ports:
      - "${FRONTEND_PORT-5173}:5173"
    volumes:
      - "./frontend:/frontend"

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db