services:
  backend:
    image: attiladudas/backend:latest
    build:
      context: ./backend
    command: ["./run-server", "-host", "0.0.0.0", "-port", "80"]
    ports:
      - "127.0.0.1:${BACKEND_PORT-8080}:80"

  frontend:
    image: frontend
    build: ./astro-frontend
    working_dir: /astro-frontend
    command: >
      bash -c "pnpm install
      && pnpm dev"
    environment:
      - PUBLIC_DATEK_WS_URL=ws://127.0.0.1:${BACKEND_PORT-8080}
    ports:
      - "127.0.0.1:${FRONTEND_PORT-4321}:4321"
    volumes:
      - "./astro-frontend:/astro-frontend"
