services:
  backend:
    image: attiladudas/backend:latest
    user: backend
    build:
      context: ./backend
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - API_MIGRATIONS_DIR=/migrations
      - API_MEDIA_DIR=/media
      - API_PRIVATE_KEY
      - API_PUBLIC_KEY
    command: ["./run-server", "-host", "0.0.0.0", "-port", "80"]
    volumes:
      - "./.tmp/media:/media"
    ports:
      - "127.0.0.1:${BACKEND_PORT-8080}:80"

  frontend:
    image: frontend
    build: ./astro-frontend
    working_dir: /astro-frontend
    command: >
      bash -c "pnpm install
      && pnpm dev"
    environment:
      - PUBLIC_DATEK_WS_URL=ws://127.0.0.1:${BACKEND_PORT-8080}
    ports:
      - "127.0.0.1:${FRONTEND_PORT-4321}:4321"
    volumes:
      - "./astro-frontend:/astro-frontend"
