services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_USER=${APP_DB_USER}
      - POSTGRES_DB=${APP_DB_NAME}
    ports:
      - "127.0.0.1:${APP_DB_PORT-5432}:5432"
    healthcheck:
      test: "PGPASSWORD=${APP_DB_PASSWORD} psql -U ${APP_DB_USER} -h 127.0.0.1 -p 5432 -d ${APP_DB_NAME} -c 'SELECT 1'"
      interval: 1s
      timeout: 1s
      retries: 5
