- name: copy nginx config
  template:
    src: ../templates/nginx.conf
    dest: "/etc/nginx/sites-available/{{ app_name }}.conf"
  notify:
    - restart nginx

- name: create symlink
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}.conf"
    state: link