- name: copy rsyslog config
  template:
    src: ../templates/rsyslog.conf
    dest: "/etc/rsyslog.d/{{ app_name }}.conf"
  notify:
    - restart rsyslog

- name: copy logrotate
  template:
    src: ../templates/logrotate
    dest: "/etc/logrotate.d/{{ app_name }}"