- name: update backend
  copy:
    src: ../../.dist/backend
    dest: /opt/{{ app_name }}/.
    owner: www-data
    group: www-data
    mode: "u=rwx,g=r,o=r"
  notify:
    - restart service

- name: copy starter script
  template:
    src: ../templates/run_server.sh
    dest: "{{ starter_script }}"
    owner: www-data
    group: www-data
    mode: "u=rwx,g=r,o=r"
  notify:
    - restart service

- name: update frontend
  copy:
    src: ../../.dist/frontend
    dest: /opt/{{ app_name }}/.
    owner: www-data
    group: www-data
  notify:
    - restart service

- name: run migrations
  command:
    cmd: "/opt/{{ app_name }}/backend/migrate up"

- name: create media dir
  file:
    path: "{{ media_dir }}"
    state: directory
    owner: www-data

- name: copy systemd service file
  template:
    src: ../templates/systemd.service
    dest: "/etc/systemd/system/{{ service }}"
  notify:
    - restart service

- name: copy env file
  template:
    src: ../templates/env
    dest: "{{ environment_file }}"
  notify:
    - restart service

- name: start service
  systemd:
    name: "{{ service }}"
    state: started
    enabled: yes
    daemon_reload: yes
