name: CI Pipeline

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.0'
    - uses: extractions/setup-just@v1

    - name: Test
      env:
        POSTGRES_HOST: 127.0.0.1
        POSTGRES_PORT: 5432
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test
      shell: bash
      working-directory: ./backend
      run: |
        docker compose up -d

        PROJECT_DIR="$(pwd)"
        export PROJECT_DIR

        MIGRATIONS_DIR="$PROJECT_DIR/db/migrations"
        export MIGRATIONS_DIR

        just migrate up
        go install gotest.tools/gotestsum@latest
        status=0
        just test-cover || status=$?
        docker compose down -v
        exit $status

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: backend/.coverage
        token: ${{ secrets.CODECOV_TOKEN }}
