name: CI Pipeline

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.22.0'
    - uses: extractions/setup-just@v1

    - name: Test backend
      shell: bash
      working-directory: ./backend
      run: |
        go install gotest.tools/gotestsum@latest
        just test-cover

    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Check frontend
      shell: bash
      working-directory: ./frontend
      run: |
        pnpm install && pnpm check

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: backend/.coverage
        token: ${{ secrets.CODECOV_TOKEN }}
